test new action versions

diff --git a/.github/workflows/AutomateRelease.yml b/.github/workflows/AutomateRelease.yml
--- a/.github/workflows/AutomateRelease.yml
+++ b/.github/workflows/AutomateRelease.yml
@@ -45,12 +45,81 @@ on:
         required: false
 
 jobs:
-  update-rule-metadata:
+  pre-release-checks:
     runs-on: ubuntu-latest
     permissions:
-      id-token: write
+      statuses: read
       contents: write
       pull-requests: write
     steps:
+      - name: Check Releasability Status
+        uses: SonarSource/release-github-actions/check-releasability-status@03368d584ef1b9bdcc0d786f99246f669ac6030c
+      
       - name: Update Rule Metadata
-        uses: SonarSource/release-github-actions/update-rule-metadata@nw/add-update-rule-metadata-action
+        id: update-rule-metadata
+        uses: SonarSource/release-github-actions/update-rule-metadata@03368d584ef1b9bdcc0d786f99246f669ac6030c
+      
+      - name: Check Rule Metadata Changes
+        if: steps.update-rule-metadata.outputs.has-changes == 'true'
+        run: |
+          echo "::error::Rule metadata changes detected. The generated PR needs to be merged first before continuing with the release."
+          echo "::error::Pull Request URL: ${{ steps.update-rule-metadata.outputs.pull-request-url }}"
+          echo "::error::Please merge the PR and restart this workflow."
+          exit 1
+
+  prepare-release:
+    runs-on: ubuntu-latest
+    needs: pre-release-checks
+    permissions:
+      statuses: read
+      contents: read
+      id-token: write
+    outputs:
+      release-version: ${{ steps.get-release-version.outputs.release-version }}
+      jira-version-name: ${{ steps.get-jira-version.outputs.jira-version-name }}
+      release-notes: ${{ steps.get-jira-release-notes.outputs.release-notes }}
+      jira-release-url: ${{ steps.get-jira-release-notes.outputs.jira-release-url }}
+    steps:
+      - name: Get Release Version
+        id: get-release-version
+        uses: SonarSource/release-github-actions/get-release-version@03368d584ef1b9bdcc0d786f99246f669ac6030c
+
+      - name: Get Jira Version
+        id: get-jira-version
+        uses: SonarSource/release-github-actions/get-jira-version@03368d584ef1b9bdcc0d786f99246f669ac6030c
+
+      - name: Get Jira Release Notes
+        id: get-jira-release-notes
+        uses: SonarSource/release-github-actions/get-jira-release-notes@03368d584ef1b9bdcc0d786f99246f669ac6030c
+
+  create-release-ticket:
+    runs-on: ubuntu-latest
+    needs: prepare-release
+    permissions:
+      id-token: write
+    steps:
+      - name: Create Jira Release Ticket
+        uses: SonarSource/release-github-actions/create-jira-release-ticket@03368d584ef1b9bdcc0d786f99246f669ac6030c
+        with:
+          project-name: ${{env.PROJECT_NAME }}
+          short-description: ${{ inputs.short_description }}
+          sq-compatibility: ${{ inputs.sq_compatibility }}
+          jira-release-url: ${{ needs.prepare-release.outputs.jira-release-url }}
+          start-progress: true
+
+  publish-github-release:
+    name: Publish github release
+    runs-on: ubuntu-latest
+    needs: prepare-release
+    permissions:
+      id-token: write
+      contents: write
+      actions: write
+    steps:
+      - name: Publish GitHub Release
+        uses: SonarSource/release-github-actions/publish-github-release@update_publish-github-release
+        with:
+          release-version: ${{ needs.prepare-release.outputs.release-version }}
+          release-notes: ${{ needs.prepare-release.outputs.release-notes }}
+          release-workflow: 'sonar-release.yml'
+          draft: true
